import os

BROKER_URL = os.environ.get('CLOUDAMQP_URL')
CELERY_TASK_SERIALIZER = 'json'
MONGOLAB_URI = os.environ.get('MONGOLAB_URI')

CLIENT_KEY= os.environ.get('CLIENT_KEY')
CLIENT_SECRET= os.environ.get('CLIENT_SECRET')
ACCESS_TOKEN= os.environ.get('ACCESS_TOKEN')
ACCESS_SECRET= os.environ.get('ACCESS_SECRET')

# CELERY_TASK_SERIALIZER = 'json'
# BROKER_POOL_LIMIT = 1